# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: megusta
email: d u a r t e _ e l i a n a at hotmail . com
description: > # this means to ignore newlines until "baseurl:"
  The goal of this page is to post recipes I find delicious and useful to
  be on a healthy diet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emduart2.github.io/megusta" # the base hostname & protocol for your site
twitter_username: notwitter
github_username:  emduart2

# Build settings
markdown: kramdown
